### ISSUE TITLE
Module does not render templates

### ISSUE THREAD

**Issue by mmcasavant** [Email-builder/email-builder-example#1]
I've triple checked the configuration for my grunt file and made sure all the dependencies are installed for this module. Unfortunately the tool does not render the files as input in the configuration or any files at all.

http:stackoverflow.com/questions/27558551/why-wont-grunt-run-my-task/27558724#27558724

**Comment by yargalot** [comment]
Looks like that got answered there, was a watch thing.

Gonna close, thanks!
